apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: demo-api
  namespace: job-demo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: job-scheduler-keda-demo
      app.kubernetes.io/component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: demo-scheduler
  namespace: job-demo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: job-scheduler-keda-demo
      app.kubernetes.io/component: scheduler
