name: job-scheduler-keda-demo

services:
  rabbitmq:
    image: rabbitmq:4.1-management-alpine
    container_name: job-demo-rabbitmq
    hostname: job-demo-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:?RABBITMQ_USERNAME is required}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:?RABBITMQ_PASSWORD is required}
    ports:
      - "15673:5672"
      - "15674:15672"
    volumes:
      - job-demo-rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 30
    restart: unless-stopped

volumes:
  job-demo-rabbitmq-data:
    name: job-demo-rabbitmq-data
