package io.github.mikuwwl.matchingreplay.failure;

public enum ReplayFailureCode
{
    RECORDING_NOT_FOUND,
    INVALID_REPLAY_RANGE,
    CHECKPOINT_RECORDING_MISMATCH,
    CHECKPOINT_CORRUPTED,
    SBE_DECODE_FAILED,
    UNSUPPORTED_SCHEMA,
    UNSUPPORTED_TEMPLATE,
    SEQUENCE_GAP,
    NO_PROGRESS_TIMEOUT,
    MAXIMUM_REPLAY_DURATION,
    CHECKPOINT_WRITE_FAILED,
    COMPLETION_PROOF_WRITE_FAILED,
    COMPLETION_PROOF_ALREADY_EXISTS,
    COMPLETION_PROOF_CORRUPTED,
    VERIFICATION_MISMATCH,
    REPLAY_IMAGE_UNAVAILABLE,
    INTERNAL_ERROR
}
